---
- name: SCHEDULER | Create directory structure
  with_items:
    - "{{ airflow_folder_systemd }}"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0744
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"

- name: SCHEDULER | Copy systemd service file
  template:
    src: airflow-scheduler.service.j2
    dest: "{{ airflow_folder_systemd }}/airflow-scheduler.service"
    mode: 0644
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
  notify:
    - restart scheduler

- name: SCHEDULER | Create systemd service symlink
  file:
    src: "{{ airflow_folder_systemd }}/airflow-scheduler.service"
    dest: "{{ airflow_os_folder_systemd }}/airflow-scheduler.service"
    state: link
    force: yes
  notify:
    - restart scheduler

- name: SCHEDULER | Enable systemd service
  systemd:
    name: airflow-scheduler
    enabled: yes
    daemon_reload: yes
