---
- name: Install airflow common components
  import_tasks: install_common.yml
  tags:
    - always

- name: Install airflow flower
  import_tasks: install_flower.yml
  when: "'flower' in airflow_components"
  tags:
    - flower

- name: Install airflow scheduler
  import_tasks: install_scheduler.yml
  when: "'scheduler' in airflow_components"
  tags:
    - scheduler

- name: Install airflow web
  import_tasks: install_web.yml
  when: "'web' in airflow_components"
  tags:
    - web

- name: Install airflow worker
  import_tasks: install_worker.yml
  when: "'worker' in airflow_components"
  tags:
    - worker


# TODO
# install kerbeos
